### ISSUE TITLE
Just a couple of questions

### ISSUE THREAD

**Issue by JustAnEdiot** [saimoomedits/dotfiles#11]
Hey I'm back!
Sorry for bothering you again...
I just got it installed, but I'm just wondering how I can remove the battery indicators, and also I'm having issues with the material design font.

Any help would be greatly appreciated, thanks!

**Comment by saimoomedits** [comment]
hey @JustAnEdiot , 
to remove the battery indicator from bar. its quite simple
edit `~/.config/awesome/layout/bar.lua`
there, remove line 298 to 302

and as for the icon fonts,
* you need [material icons round](https://developers.google.com/fonts/docs/material_icons) font for icons
* and as for the ui its [roboto](https://fonts.google.com/specimen/Roboto).

also, a whole new setup will be committed soon, with much better support and customization 

thanks for sharing your issue

**Comment by JustAnEdiot** [comment]
Hey I'm back once again with a question;

Is there a way to disable the headerbars from either your theme or apps that have headerbars, such as gnome apps?
