### ISSUE TITLE
.themes is missing

### ISSUE THREAD

**Issue by raluvy95** [saimoomedits/dotfiles#12]
Step 4 says it needs to copy .themes to user's themes, but is absent in this repo.

**Comment by saimoomedits** [comment]
@raluvy95 , my bad. forgot to add it.

1. you can get the theme from the [aur](https://aur.archlinux.org/packages/materia-theme-git) 

or

2. [build it from source](https://github.com/nana-4/materia-theme) 

and copy the gtk-themes to your .themes (if you used the 2nd method)
