### ISSUE TITLE
Issues while installing

### ISSUE THREAD

**Issue by Flojomojo** [saimoomedits/dotfiles#14]
Hey!
Im having an issue while installing. After follwing all the required steps an error occurs: `/usr/share/lua/5.4/namespace.lua:158: Typelib file for namespace 'Playerctl' (any version) not found` 
Google doesn't seem to help and neither does reinstall.
Thanks for the help!

**Comment by saimoomedits** [comment]
Hey thanks for the feedback
Do you have `playerctl` installed?

if not, install `playerctl` using your distro's package manager.

on Arch Linux, the command would be: 
`sudo pacman -S playerctl`

**Comment by Flojomojo** [comment]
Yep that was the issue, thanks 😄
