### ISSUE TITLE
Problems with ncmpcpp album-art

### ISSUE THREAD

**Issue by Anthropicalluv** [saimoomedits/dotfiles#16]
Im on arch and when a press mod+s to display the custom ncmpcpp ui and when i play a song i get unknown artist and album-art, my songs are flac and have embedded album-art and artist information 

https://user-images.githubusercontent.com/91760593/168384790-d6f3c7d7-f601-4d92-9f63-18f1aa13b3bb.mp4

**Comment by sohumor** [comment]
also, im aware the video doesnt have any sound, it was just to display that there was no album art

**Comment by saimoomedits** [comment]
hey thanks for sharing your issue @Father-Dimi ,
do you have `mpDris2` installed

the music-info uses bling's playerctl signal
and `mpDris2` adds MPRIS to mpd. which can be used with `playerctl`

you should install mpDris2 with the following: `sudo pacman -S mpDris2`

**Comment by sohumor** [comment]
I preformed your recommended command (note; arch does not officially support that package so i used aur) and realized that the build failed, i did install all previous requirements from your readme and must of not realize that this package failed, so i built it from source and album-art and artist info started working, thanks for the help

closing this issue
