### ISSUE TITLE
Typo in setup instructions (package names)

### ISSUE THREAD

**Issue by jclicodes** [saimoomedits/dotfiles#17]
Might save a minute or two when setting this up from scratch on a new system.

Alacritty -> alacritty
mpDris2 -> mpdris2

**Comment by saimoomedits** [comment]
fixed in commit [4c715be](https://github.com/saimoomedits/dotfiles/commit/4c715be3d6f83f770b9df7ad20990f232584918a)

**Comment by saimoomedits** [comment]
thanks
