### ISSUE TITLE
(Suggestion) Make the lockscreen clock look like Android 12

### ISSUE THREAD

**Issue by inari-codes** [saimoomedits/dotfiles#18]
I stumbled on this repository from your post in r/unixporn and it looks great!

However the clock style in the lockscreen looks like Android 9 - Android 11 instead

![lockscreen](https://user-images.githubusercontent.com/85934291/168424798-d5a101e2-a6a9-45c0-9705-cd94a5e9f192.png)

![Android_11_Lock_Screen](https://user-images.githubusercontent.com/85934291/168424844-cdc8dee5-0acd-4bcc-bf41-697226007eaf.png)

But i think this dotfiles is supposed to look like Material 3 (as seen in Android 12) so maybe it should look like this:

![thread-133337499-1497477143686209883](https://user-images.githubusercontent.com/85934291/168424921-d4540df6-25c3-4481-8aa7-45c919caff37.png)

But i'm worried that the newer clock style wastes more screen space, anyway this is just a suggestion, you can close it without any action if you want

**Comment by saimoomedits** [comment]
hey @nguyensang28 , thanks for the suggestions
i will definitely try it when i am free

keeping this issue until its done.

**Comment by saimoomedits** [comment]
tried to keep it minimal, 

but done.
