### ISSUE TITLE
AwesomeWM fails to load.

### ISSUE THREAD

**Issue by ghost** [saimoomedits/dotfiles#2]
My issue is that module 'mods.rubato' is not found, do you know how to solve this, I have followed the install guide.

**Comment by saimoomedits** [comment]
you have to clone  [rubato](https://github.com/andOrlando/rubato) and [bling](https://github.com/BlingCorp/bling) repos into mods directory in `~/.config/awesome/mods/`

ill fix it now

**Comment by saimoomedits** [comment]
fixed
[0fe2f15](https://github.com/saimoomedits/dotfiles/commit/0fe2f156da5bc8c918d4802394fc75817c1b3eae)
