### ISSUE TITLE
Awesome error in switcher.lua

### ISSUE THREAD

**Issue by ViiEx** [saimoomedits/dotfiles#20]
## Description
Im trying to run the dotfiles in `Ubuntu  LST 22.04` having build the `awesomewm` from source on github.

I used `Lua 5.1` to build it and the the start I thought that may be the problem so I installed `Lua 5.4` with no results.

## Error message
``` text
error while running function!
stack traceback:
    [C]: ?
    [C]: in function 'require'
    ...user/.config/awesome/mods/layout-machi/init.lua:4: in main chunk
    [C]: in function 'require'
    /home/user/.config/awesome/config/keys.lua:9: in main chunk
    [C]: in function 'require'
    /home/user/.config/awesome/config/init.lua:1: in main chunk
    [C]: in function 'require'
    /home/user/.config/awesome/rc.lua:41: in main chunk
error: error loading module 'mods.layout-machi.switcher' from file '/home/user/.config/awesome/mods/layout-machi/switcher.lua':
    /home/user/.config/awesome/mods/layout-machi/switcher.lua:357: '=' expected near 'continue'
```

Any suggestions?
Thanks for your time!

**Comment by saimoomedits** [comment]
hey @ViiEx , which lua version are you using right now?

`lua -v`

**Comment by ViiEx** [comment]
I'm using Lua 5.1.5

**Comment by saimoomedits** [comment]
ahh, you should have lua 5.4.4, thats the latest release of lua.

**Comment by ViiEx** [comment]
I changed my lua version by linking the version 5.4 to the lua exec file using the following

```bash
 sudo ln -sf /usr/bin/lua5.4 /usr/bin/lua
```

Now when I execute `lua -v` I do get the right version
```bash
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
```

But I'm still getting the same error from awesome.

**Comment by saimoomedits** [comment]
did you try recompiling awesomewm with lua 5.4.4?

**Comment by ViiEx** [comment]
I have being trying it for few hours. Unrelated with this issue but I cant compile awesome with `lua 5.4.4` since `lgi` is still not available for it. I 'm trying to build with `lua 5.3` but not much luck yet

**Comment by saimoomedits** [comment]
I see, thats the problem. you need to compile awesomewm with lua 5.4.4.

but this can however be fixed by disabling `layout-machi` (the module that causes this error)

1. Disable `layout-machi` layout

- in `.config/awesome/config/tags.lua`
- remove line `7` and `19 to 25`
- next remove it from global layouts by editing line 39
         - `l.tile, l.floating, l.floating, mstab, deck })`

2. disable `layout-machi` keybinding
- in `.config/awesome/config/keys.lua`
- remove or comment-out line `9`


The steps above disables `layout-machi`, which is a AwesomeWm manual layout with interactive editor.

if you need more help, feel free to re-open this issue

**Comment by ViiEx** [comment]
For anyone else having issues like me I managed to build awesome with `lua 5.4.4` but compiling `lgi` myself using the following command

```bash
make -C . PREFIX=/usr LUA_VERSION=5.4 LUA_CFLAGS="$(pkg-config --cflags lua5.4)"
```

and then 

```bash
sudo make install LUA_VERSION=5.4
```
