### ISSUE TITLE
Lockscreen locked (for real) after sleep

### ISSUE THREAD

**Issue by EvanKoe** [saimoomedits/dotfiles#21]
Hi ! 
I encountered a bug using this config, with the lockscreen : when I lock the screen, I can enter the password with the little animation around the locker. But when my computer goes to sleep, and I wake it up pressing space, the lockscreen is displayed, but I cannot do any input, there is no animation on the locker when a key is pressed, and I cannot unlock my computer, so I have to force restart.  
  
More infos :  
OS : Arch Linux  
Kernel version : linux 5.17.7  
awesome version : 4.3-1360-gc539e0e43 (Too long)  
picom version : vgit-4107

**Comment by saimoomedits** [comment]
hoi, @EvanKoe , thanks for informing..

but... :neutral_face: 

I am a bit confused, can you please give more details on whats happening? :thinking: 

for me it works perfectly, even after waking up from sleep. :moon:

**Comment by EvanKoe** [comment]
Hi ! 

Thanks for answering 😀 

The problem is I cannot unlock the computer after putting it into sleep due to inactivity, or by closing the lid. 

Once I open up the lid again and wake the screen from sleep, the lockscreen just doesn't respond to any input, so I cannot unlock it.

In such a case I can do nothing but restart using the power button...

Do you need any other info ? Just ask 😄

**Comment by saimoomedits** [comment]
@EvanKoe , I tried to replicate what you did. :sunglasses: 

but it works perfectly for me, just after i press the `space bar` to wake up. I can re-enter my password and log back in :cry:

**Comment by EvanKoe** [comment]
![a28z8Yf.png](https://user-images.githubusercontent.com/72010109/169020979-46372ee0-6022-464b-b0e3-c54ecf196489.png)

xD 
Jokes aside, I will try to debug it from myself, maybe it's a problem that's specific to my computer.

Thanks anyway !

**Comment by EvanKoe** [comment]
I also have a problem when I enter the wrong password. It freezes for a second, then unlocks the computer and freezes again. That's really strange 😅

**Comment by saimoomedits** [comment]
haha nice meme XD

i added a new lockscreen. i mean a completely new setup just now.

maybe it might work now.

**Comment by saimoomedits** [comment]
reopen the issue if needed :cry:
