### ISSUE TITLE
Screenshot and colorpicker not working for me [Quest]

### ISSUE THREAD

**Issue by wiredmatt** [saimoomedits/dotfiles#23]
Hi, first of all amazing work.

I followed the installation guide in the README, and almost everything is working as it should, but whenever I press PrintScreen key or Win + R I'm not getting the expected functionality from either. I have tried checking my awesome logs but there's nothing significant there. I also tried changing the keybinds but that didn't work either. I have the required dependencies installed, what may the problem be? Thanks in advance.

**Comment by saimoomedits** [comment]
Hello @system32uwu ,

sorry about that, both the script should actually be in `~/.scripts/awesome/`. I mistyped it.

**Comment by wiredmatt** [comment]
That was it, thanks!
