### ISSUE TITLE
Battery error

### ISSUE THREAD

**Issue by dung8466** [saimoomedits/dotfiles#27]
got error:
/.config/awesome/mods/battery-widget/init.lua:125:attempt to index a nil value (field 'device')
My spec: laptop msi modern 15 r5-5500u, amd radeon graphics
Distro: Arch

**Comment by kunihir0** [comment]
I got around this by commenting out the battery signal since I didn't need it for my machine

`awesome/signal/init.lua`

for my setup without a battery I had to remove some lines from the bar folder in `layout/bar/init.lua`, atm I am still getting rid of the battery stuff 

I think down the road there needs to be a way to differentiate desktop users from laptop users

**Comment by kunihir0** [comment]
I think down the road there needs to be a way to differentiate desktop users from laptop users

**Comment by dung8466** [comment]
i'm on a laptop so i can't do that. is there another way to fix it?

**Comment by unix-parrot** [comment]
@dung8466 , did you install `Upower`? its probably cuz of that.

`sudo pacman -S upower`

**Comment by dung8466** [comment]
i already installed upower so i don't think that the issue

**Comment by unix-parrot** [comment]
wierd, it works perfectly for me with no errors

**Comment by kam1xgod** [comment]
@dung8466, I don't really know if it will help in your case, but switching

```
use_display_device = false
```

in ~/.config/awesome/mods/battery-widget/init.lua (line 113) to

```
use_display_device = true
```

works for me.

According to README for UPower Battery Widget:

> With the parameter `use_display_device = true`, the battery widget will automatically monitor the _display device_.
> 
> If you want to manually set which device to monitor, you can use the `device_path` parameter.
> 
> ```lua
> local my_battery_widget = battery_widget{
>     screen = s,
>     device_path = '/org/freedesktop/UPower/devices/battery_BAT0',
>     widget_template = wibox.widget.textbox
> }
> ```

Note: you can find it in 
```
~/.config/awesome/mods/battery-widget/README.md
```

**Comment by dung8466** [comment]
thank you. that work for me
