### ISSUE TITLE
[Quest] Is there a way to disable titlebars on specific applications?

### ISSUE THREAD

**Issue by JustAnEdiot** [saimoomedits/dotfiles#28]
I cannot for the life of me figure out how to do this manually, so I came here to ask!

**Comment by unix-parrot** [comment]
u can add the application class to `awesome/config/rulses.lua`
under titlebar rules add 

```lua
class = { "class of app", "another one" }
``` 

i think it should disable titlebars.

**Comment by JustAnEdiot** [comment]
thank you so much! :3
