### ISSUE TITLE
Errors during startup

### ISSUE THREAD

**Issue by JustAnEdiot** [saimoomedits/dotfiles#3]
Hey! I'm completely new to theming awesome, and I'm stumped.
I followed your instructions, and I'm now getting an error that says;

**Oops, there were errors during startup!**
error while running function!
stack traceback:
         /home/main/.config/awesome/config/error_notif.lua:5 in main chunk
        [C]: in function 'require'
        /home/main/.config/awesome/rc.lua:34: in main chunk
error: /home/main/.config/awesome/config/error_notif.lua:5: attempt to call a nil value (field 'connect_singal')

Any help would be greatly appreciated! :3

**Comment by saimoomedits** [comment]
hey thanks for replying. may I know which awesome package you installed? awesome or awesome-git?

**Comment by unix-parrot** [comment]
yeah, you need awesome-git

**Comment by unix-parrot** [comment]
yeah, awesome-git is the solution

**Comment by saimoomedits** [comment]
I am closing this issue,
feel free to open it when you need
