### ISSUE TITLE
How to add new workspaces and systray

### ISSUE THREAD

**Issue by Underscore30** [saimoomedits/dotfiles#31]
Hello, using this as my daily driver for a few weeks now and loving it. The only thing I really need is to make the number of workspaces higher (4 sometimes is not enough) and adding a way to see the systray(I tried other systray programs like stalonetray but they don't work so well). 

Could you please point me in the right direction on how I could add these things?

**Comment by Fennix900** [comment]
Take a look in the tags.lua layout machi.
I think playing around with this lines of code should work

**Comment by saimoomedits** [comment]
add as many workspaces you need in this line `config/tags.lua` :
https://github.com/saimoomedits/dotfiles/blob/fb5efb1ddbb9c260771dfa96814c346663204666/.config/awesome/config/tags.lua#L28

I personally don't use systray but you can add one.
documentation for systray: https://awesomewm.org/apidoc/widgets/wibox.widget.systray.html
