### ISSUE TITLE
Facing issue in installing dependency

### ISSUE THREAD

**Issue by tirtharajsinha** [saimoomedits/dotfiles#33]
![image](https://user-images.githubusercontent.com/64787936/184021348-f27a3025-fe90-43e1-aadc-3d399069c470.png)

sorry to bother you but I'm actually new to this thing.
Getting error in installation. please help.

**Comment by blissio** [comment]
change xorg-init to xorg-xinit that should fix it

**Comment by shabbir23ah** [comment]
![IMG_20220812_015910](https://user-images.githubusercontent.com/56797263/184236430-f9f10972-ca5a-4b75-98c8-68528d4e2de8.png)
I'm not getting what's happened here. Could you help

**Comment by Biaogo** [comment]
> ![IMG_20220812_015910](https://user-images.githubusercontent.com/56797263/184236430-f9f10972-ca5a-4b75-98c8-68528d4e2de8.png)我不明白这里发生了什么。 你能帮忙吗

This is a dependency conflict, delete the conflicting package

```
pacman -Rdd gnome-bluetooth pipewire-support
```
