### ISSUE TITLE
How to change the battery

### ISSUE THREAD

**Issue by blissio** [saimoomedits/dotfiles#34]
In the widget the battery is set BAT0, i have BAT1 on my laptop and because of that it crashes awesome and does not let me run the rice i tried changing it in `.config/awesome/mods/battery-widget/init.lua` the line where in says `local bat0_path = '/org/freedesktop/UPower/devices/battery_BAT0'` any help?

**Comment by saimoomedits** [comment]
uncomment this line with `--`
https://github.com/saimoomedits/dotfiles/blob/fb5efb1ddbb9c260771dfa96814c346663204666/.config/awesome/signal/init.lua#L1

this will disable the battery signal altogether
