### ISSUE TITLE
Is it possible to have window manager independent control center with the look you have achieved in awesome wm?

### ISSUE THREAD

**Issue by Partha2003** [saimoomedits/dotfiles#36]
**Description**
Hi, 
I think this might be a bit off topic but i was in search of a similar control center to use with my open box config. I was wondering if any workaround or alternative could be possible.

**Comment by saimoomedits** [comment]
Hey thanks,

I am sorry but this isn't possible with these widgets since they are created and works on awesomeWM only. but you can use [eww](https://github.com/Elkowar/eww) to re-create/create widgets in other wm/de's.
