### ISSUE TITLE
Make sure the commands are still working

### ISSUE THREAD

**Issue by AmmarHaddadi** [saimoomedits/dotfiles#38]
hey , some paths u gave seems to be wrong and instead I had to enter the extras folder , and in the end it didn't work but giving me a bunch of errors
also , with all respect , how stupid are you to include firefox, neovim, and the whole linux kernel 419 with a bunch of ther usless stuff , I spent hours removing them , please , only necessary stuff , also mention that mpv is the music player , some ppl like me don't wanna have that

**Comment by saimoomedits** [comment]
ok
