### ISSUE TITLE
Volume controls not working

### ISSUE THREAD

**Issue by the-merky** [saimoomedits/dotfiles#51]
So I installed your config. After some hassle, I managed  to get to work ( I think there is a typo in the dependency install command). Unfortunately, **the volume controls don't seem to work.** The brightness works just fine. To make sure I have everything, I reinstalled the  dependencies. Seemingly no effect. Am I missing some kind of package? I am on arch.

**Comment by ghost** [comment]
Leave your solution before closing it, people.

**Comment by the-merky** [comment]
Dear, @wannafedora sorry about that. This incident happened a while ago and I don't remember what was my solution or whether I even had one. I am terribly sorry about this and the late reply! I will reopen this issue so if anyone finds a solution they can add it.

**Comment by ghost** [comment]
Thank you @The-Merky. It just is really annoying when that happens, because when people have the same error, they have no idea how to fix it. Did you change your audio package, or did you change the dot files?

**Comment by the-merky** [comment]
Dear @wannafedora I am almost sure I installed a package like `pulseaudio`. Hope this gets resolved soon!
